const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');
const { listCodexSessions, readCodexSession, assertCodexSessionIdle } = require('./codex-sessions.cjs');

test('local history pages preserve offsets, ignore instructions, and wait for complete lines', t => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'codex-import-'));
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  const rollout = path.join(home, 'rollout.jsonl');
  const db = new DatabaseSync(path.join(home, 'state_5.sqlite'));
  db.exec('CREATE TABLE threads(id TEXT, title TEXT, cwd TEXT, updated_at INTEGER, rollout_path TEXT)');
  db.prepare('INSERT INTO threads VALUES (?,?,?,?,?)').run('selected', 'My session', '/tmp/work', 123, rollout);
  db.close();
  const event = (role, text) => JSON.stringify({ type: 'response_item', timestamp: '2026-09-01T00:00:00Z', payload: { type: 'message', role, content: [{ text }] } });
  fs.writeFileSync(rollout, event('developer', 'private instructions') + '\n' + event('user', 'héllo') + '\n' + event('assistant', 'answer'));
  assert.equal(listCodexSessions({}, home).sessions.length, 1);
  const first = readCodexSession({ id: 'selected' }, home);
  assert.deepEqual(first.messages.map(m => m.body), ['héllo']);
  assert.deepEqual(readCodexSession({ id: 'selected', offset: first.nextOffset }, home).messages, []);
  fs.appendFileSync(rollout, '\n');
  const second = readCodexSession({ id: 'selected', offset: first.nextOffset }, home);
  assert.deepEqual(second.messages.map(m => m.body), ['answer']);
  assert.equal(second.messages[0].index, first.nextOffset);
  assert.throws(() => readCodexSession({ id: '../rollout' }, home), /no longer exists/);
  fs.appendFileSync(rollout, JSON.stringify({ type: 'event_msg', payload: { type: 'task_started' } }) + '\n');
  assert.throws(() => assertCodexSessionIdle('selected', home), /still working elsewhere/);
  fs.appendFileSync(rollout, JSON.stringify({ type: 'event_msg', payload: { type: 'task_complete' } }) + '\n');
  assert.doesNotThrow(() => assertCodexSessionIdle('selected', home));
  fs.writeFileSync(rollout, Array.from({ length: 201 }, (_, i) => event('assistant', `message ${i}`)).join('\n') + '\n');
  const batch = readCodexSession({ id: 'selected' }, home);
  assert.equal(batch.messages.length, 200);
  assert.equal(batch.hasMore, true);
  fs.appendFileSync(rollout, event('assistant', 'added after snapshot') + '\n');
  const last = readCodexSession({ id: 'selected', offset: batch.nextOffset, snapshotEnd: batch.snapshotEnd }, home);
  assert.deepEqual(last.messages.map(m => m.body), ['message 200']);
  assert.equal(last.hasMore, false);
});
